/*
# TÜBİTAK Sanayi Destekleri 2026 çağrı kataloğu

1. Değişiklikler
- PDF kaynağındaki 20 ulusal ve 6 uluslararası ortak destek programı `funds` tablosuna eklenir.
- Her kayıtta çağrı kodu, program adı, kurum, destek türü, bütçe, süre, son başvuru bilgisi, uygunluk koşulları, gerekli belgeler ve teknik kapsam bulunur.
- Mevcut programlar silinmez; aynı kod veya ad varsa yeniden eklenmez.

2. Görünürlük
- Tüm çağrılar mevcut Açık Çağrılar ekranında listelenir.
- Tarihi veya durumu PDF'de kesinleşmemiş programlar da katalogda görünür; bu durum açıklama ve başvuru tarihi alanlarında belirtilir.

3. Güvenlik
- Yeni tablo oluşturulmaz ve RLS politikaları değiştirilmez.
- Mevcut `funds` tablosunun anon + authenticated katalog erişimi kullanılır.

4. Kaynak notu
- Bilgiler 21 Eylül 2026 tarihli TÜBİTAK Sanayi Destekleri PDF özetinden aktarılmıştır.
- Başvuru öncesinde resmi çağrı metnindeki güncel şartlar kontrol edilmelidir.
*/

INSERT INTO funds (
  name, provider, type, budget, min_trl, max_trl, sectors, description, code,
  application_url, deadline, duration, max_budget_per_project, support_rate,
  eligibility, required_docs, technical_scope, status
)
SELECT * FROM (VALUES
  ('Sanayi Ar-Ge Projeleri Destekleme Programı', 'TÜBİTAK', 'kamu', 'Proje başına 20.000.000 TL''ye kadar', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1501 kodlu ulusal hibe programı. KOBİ ölçeğindeki kuruluşların Ar-Ge, teknoloji geliştirme ve yenilikçilik faaliyetlerini destekler.', '1501', '', '26.10.2026', '24 ay (şartlı uzatmayla en fazla 36 ay)', '20.000.000 TL', '%75 (ilk 5 proje); %60 (sonraki projeler)', ARRAY['Türkiye''de yerleşik KOBİ ölçeğinde sermaye şirketi','Kuruluş bazlı ön kayıt ve e-imza','Proje ekibinde ilgili alan lisans mezunu personel','En az 1 üniversite/araştırma kuruluşu ile işbirliği'], ARRAY['1501 Proje Öneri Başvuru Formu (AGY100)','Kuruluş bazlı ön kayıt','Teknik doküman ve tasarım raporu','Bütçe planlaması','İşbirliği protokolü (varsa)'], 'Ürün, süreç veya hizmet geliştirmeye yönelik ulusal sanayi Ar-Ge ve yenilik projeleri.', 'open'),
  ('Proje Pazarları Destekleme Programı', 'TÜBİTAK', 'kamu', 'Üst limit TEYDEB limit tablosuna göre', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1503 kodlu sürekli açık program. Üniversite, araştırma ve özel sektör temsilcilerini proje işbirliği için buluşturur.', '1503', '', 'Sürekli açık', 'Program duyurusuna göre', 'TEYDEB limit tablosuna göre', 'Etkinlik giderleri desteği', ARRAY['Sanayi veya ticaret odası, birlik ya da ihracatçı birliği','Etkinlikte en az bir üniversite katılımı','Kurumların Ar-Ge düşünce veya proje önerisi'], ARRAY['Proje Pazarı Öneri Bilgileri Formu (AGY 104-01)','Etkinlik/proje önerisi','Katılımcı ve bütçe bilgileri'], 'Üniversite, araştırma ve özel sektör temsilcileri arasında proje pazarı ve işbirliği ortamı oluşturulması.', 'open'),
  ('Üniversite-Sanayi İşbirliği Destek Programı', 'TÜBİTAK', 'kamu', 'Uygulama esaslarına göre belirlenir', 2, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1505 kodlu sürekli açık program. Üniversitelerdeki bilgi ve teknolojinin sanayiye aktarılmasını destekler.', '1505', '', 'Sürekli açık', 'En fazla 24 ay', 'Uygulama esaslarında belirlenir', 'KOBİ müşteride %75; büyük müşteride %60 TÜBİTAK desteği', ARRAY['Türkiye''de yerleşik sermaye şirketi müşteri kuruluş','Üniversite, vakıf üniversitesi veya araştırma hastanesi yürütücülüğü','Müşteri-yürütücü arasında işbirliği sözleşmesi'], ARRAY['PRODİS proje başvuru formu','İşbirliği sözleşmesi','Teknik proje planı','Bütçe ve görev dağılımı'], 'Üniversite ve araştırma kuruluşlarındaki bilgi ve teknolojinin ürün, süreç veya hizmete dönüştürülmesi.', 'open'),
  ('KOBİ Ar-Ge Başlangıç Destek Programı', 'TÜBİTAK', 'kamu', 'Proje bütçesi 3.500.000 TL ile sınırlı', 1, 7, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1507 kodlu KOBİ Ar-Ge başlangıç programı. Yeni ürün, mevcut ürün geliştirme ve teknoloji Ar-Ge projelerini destekler.', '1507', '', '11.11.2026', 'En fazla 18 ay', '3.500.000 TL', '%75', ARRAY['Türkiye''de yerleşik KOBİ ölçeğinde sermaye şirketi','Kuruluş bazlı ön kayıt ve e-imza','KOBİ''lerin ilk kez veya öncelikli Ar-Ge projesi','Proje konusu ile ilgili en az lisans dereceli personel'], ARRAY['1507 Proje Öneri Başvuru Formu (AGY101)','Kuruluş bazlı ön kayıt','Teknik doküman','Bütçe planlaması'], 'KOBİ''lerin rekabetçiliğini artıran yeni ürün, mevcut ürün geliştirme ve teknoloji Ar-Ge projeleri.', 'open'),
  ('Öncelikli Alanlar Araştırma Teknoloji Geliştirme ve Yenilik Programı', 'TÜBİTAK', 'kamu', 'KOBİ 20.000.000 TL; büyük ölçekli 40.000.000 TL', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1511 kodlu Teknoloji Odaklı Sanayi Hamlesi programı. Öncelikli sektörlerde yüksek katma değerli ürünlerin Türkiye''de üretimini destekler.', '1511', '', 'Çağrı takvimine bağlı', 'Çağrı duyurusuna göre, azami 36 ay', 'KOBİ 20.000.000 TL; büyük ölçekli 40.000.000 TL', 'KOBİ %75; büyük ölçekli %50 (uygulama esaslarına göre)', ARRAY['Türkiye''de yerleşik sermaye şirketi','Öncelikli ürün veya teknoloji alanında proje','Bağımsız değerlendirme ve ekonomik fizibilite şartları'], ARRAY['Bağımsız Değerlendirme Raporu','Ön kayıt onayı sonrası AGY111 formu','Ekonomik fizibilite raporu (gerektiğinde)','Teknik proje dosyası'], 'Orta-yüksek teknoloji seviyeli, katma değeri yüksek ürün ve teknolojilerin geliştirilmesi.', 'open'),
  ('Teknoloji Transfer Ofisleri Destekleme Programı', 'TÜBİTAK', 'kamu', 'Yıllık 1.250.000-1.750.000 TL', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma'], '1513 kodlu program. Üniversite bünyesindeki teknoloji transfer ofislerinin ticarileştirme faaliyetlerini destekler.', '1513', '', 'Sürekli açık', 'Program koşullarına göre', 'Kurumsal kapasite yıllık 1.250.000 TL; hedef odaklı büyüme yıllık 1.750.000 TL', '%80 kurumsal kapasite; %40-%80 hedef odaklı büyüme', ARRAY['Yükseköğretim kurumu bünyesinde TTO','YÖK onaylı TTO veya teknoloji geliştirme bölgesi yöneticiliği','Başvuruda TTO odaklı iş planı'], ARRAY['Proje öneri formu','Bütçe formu (xlsx)','Performans göstergeleri','TTO iş planı'], 'Üniversite kaynaklı bilgi ve teknolojilerin sanayiye aktarılması ve ticarileştirilmesi.', 'open'),
  ('Girişim Sermayesi Destekleme Programı (Tech-InvesTR)', 'TÜBİTAK', 'kamu', 'Tek kuruluşa azami 20.000.000 TL', 1, 7, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1514 kodlu girişim sermayesi destek programı. Erken aşama teknoloji tabanlı şirketlerin ticarileşmesini destekler.', '1514', '', 'Çağrı bekleniyor', 'Program çağrısına göre', '20.000.000 TL', '%50 hibe oranı + %10 genel gider desteği', ARRAY['TTO, TGB veya yetkili kuruluş tarafından yönetilen fona yatırım','Erken aşama teknoloji girişimlerine yatırım','Başvuru ortakları arasında gerekli uygunluk'], ARRAY['Ortak başvuru formu','Fon yatırım stratejisi','Teknoloji girişimi değerlendirme dosyası'], 'Teknoloji tabanlı şirketlerin ürün ve teknolojilerini ticarileştirmeleri için girişim sermayesi fon desteği.', 'open'),
  ('Öncül Ar-Ge Laboratuvarları Destekleme Programı', 'TÜBİTAK', 'kamu', 'Takvim yılında en fazla 25.000.000 TL', 2, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma'], '1515 kodlu program. Türkiye''deki öncül Ar-Ge laboratuvarlarının giderlerini destekler.', '1515', '', 'Sürekli açık', '5 yıl (uzatmayla en fazla 5 yıl)', '25.000.000 TL/yıl', 'Türk uyruklu personel %75; danışmanlık/eğitim %75', ARRAY['Türkiye''de yerleşik sermaye şirketi','Son 3 yılda en az 15 milyon TL Ar-Ge harcaması','Personelin en az %50''si Türk uyruklu','Toplam personelin en az üçte biri doktora sahibi'], ARRAY['Niyet beyanı','Başvuru formu','Ar-Ge laboratuvarı planı','Personel ve bütçe tablosu'], 'Öncül kuruluşların Ar-Ge laboratuvarlarının giderlerini destekleyerek seçilmiş alanlarda yüksek teknoloji geliştirme.', 'open'),
  ('Yenilik ve Girişimcilik Alanlarında Kapasite Artırılmasına Yönelik Destek Programı', 'TÜBİTAK', 'kamu', 'Çağrı duyurusuna göre', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1601 kodlu program. Girişimcilik ve yenilik alanlarında kapasite artırımını, üniversite-sanayi işbirliğini ve ekosistem gelişimini destekler.', '1601', '', 'Çağrıya bağlı', 'Çağrı duyurusuna göre', 'Çağrı duyurusuna göre', '%100''e kadar', ARRAY['Türkiye''de yerleşik şirket, üniversite, kamu araştırma merkezi veya vakıf','Yenilik ve girişimcilik alanında kapasite artırma amacı','Çağrıya göre ortaklık ve uygulama planı'], ARRAY['Çağrıya özel proje başvuru formu','Uygulama esasları','Bütçe ve kapasite geliştirme planı'], 'Girişimcilik, üniversite-sanayi işbirliği ve özel sektör Ar-Ge kapasitesinin geliştirilmesi.', 'open'),
  ('Patent Destek Programı', 'TÜBİTAK', 'kamu', 'Uluslararası patent inceleme desteği toplamı 240.000 TL', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1602 kodlu hibe/ödül programı. Ulusal ve uluslararası patent başvuru ve inceleme giderlerini destekler.', '1602', '', 'Sürekli açık', 'Program koşullarına göre', '240.000 TL toplam destek sınırı', 'Bilgi notuna göre', ARRAY['T.C. vatandaşı veya Türkiye''de yerleşik şirket, üniversite ya da kamu kurumu','TÜRKPATENT veya WIPO''ya başvuru yapılmış olması','Başvuru numarasının alınmış olması'], ARRAY['Patent başvuru ve süreç dokümanları','Başvuru numarası','Bilgi ve not formu'], 'Ülke kaynaklı ulusal ve uluslararası patent başvuru sayısını artırmaya yönelik destek.', 'open'),
  ('BiGG 1. Aşama Uygulayıcı Kuruluş Çağrısı', 'TÜBİTAK', 'kamu', 'Üst sınır çağrı metnine göre belirlenir', 1, 5, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1612 kodlu çağrı. Girişimci adaylarının teknoloji ve yenilik fikirlerini uygulayıcı kuruluşlar aracılığıyla destekler.', '1612', '', 'Kapalı (2025-1 çağrısı); yeni çağrı bekleniyor', '36 ay', 'Çağrı metnine göre', 'Uygulayıcı kuruluş desteği', ARRAY['Ortak başvuruda en fazla 4 kuruluş','Kurum başına 1 başvuru','Ortaklık ve işbirliği planı','Girişimci adayı ve uygulayıcı kuruluş bilgileri'], ARRAY['2026-2028 hedef tablosu','Program ekip özgeçmişleri','İşbirliği sözleşmesi/protokolü','Niyet mektubu'], 'Teknoloji tabanlı fikirlerin kavramsal aşamadan pazara kadar desteklenmesi.', 'open'),
  ('Teknoloji Transferi Profesyoneli Çağrısı', 'TÜBİTAK', 'kamu', '24 aylık personel ve hizmet alımı bütçesi', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma'], '1613 kodlu sürekli açık çağrı. Üniversite TTO''larına teknoloji transferi profesyoneli istihdam desteği sağlar.', '1613', '', 'Sürekli açık; 6 dönemlik takvim', '24 ay', 'A x %95 + B x %5 + C genel gider', '%60 veya %80', ARRAY['Üniversite TTO birimi','TTO mevzuatına uygun sermaye şirketi veya TGB yöneticisi','Teknoloji transfer profesyoneli istihdam planı'], ARRAY['Çevrimiçi çağrı duyurusu','TTO öz değerlendirme formu','Performans hedefleri tablosu'], 'TTO''larda yeni teknoloji transfer profesyoneli istihdamı ve mevcut profesyonellerin devamı.', 'open'),
  ('Ar-Ge Proje Değerlendirme ve İzleme Çağrısı', 'TÜBİTAK', 'kamu', 'Mali destek sağlanmıyor', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1701 kodlu hizmet çağrısı. Ar-Ge projelerinin yenilik, iş planı ve ekonomik fayda sürdürülebilirliğini değerlendirir ve izler.', '1701', '', 'Kapalı; yeni çağrı bekleniyor', 'Belirtilmemiş', 'Mali destek yok', 'Mali destek sağlanmıyor', ARRAY['Türkiye''de yerleşik KOBİ veya büyük ölçekli kuruluş','Proje bütçesi en az 5.000.000 TL','Değerlendirme ve izleme hizmeti için başvuru'], ARRAY['Çağrı metni','Proje değerlendirme dosyası','Harcama ve gider formları'], 'Ar-Ge projelerinin teknik, ekonomik ve yenilikçi yönlerinin değerlendirilmesi ve izlenmesi.', 'open'),
  ('Patent Tabanlı Teknoloji Transferi Destekleme Çağrısı', 'TÜBİTAK', 'kamu', 'Proje bütçesi en fazla 4.000.000 TL', 2, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1702 kodlu program. Üniversite ve araştırma kurumlarında geliştirilen patentli teknolojilerin sanayiye aktarılmasını destekler.', '1702', '', 'Sürekli açık', 'En fazla 60 ay; asgari proje süresi 24 ay', 'Proje bütçesi 4.000.000 TL; kavram doğrulama/prototip/test 500.000 TL', 'Temel %25; KOBİ +%15; yüksek teknoloji +%15; Yeşil Mutabakat +%15', ARRAY['Müşteri kuruluş ve teknoloji sağlayıcı ortaklığı','En az bir patent lisanslama/devralma şartı','Tescil şartı yoksa araştırma raporu'], ARRAY['Teknoloji transfer sözleşmesi','Patent özet tablosu','Tescil belgeleri','Araştırma/inceleme raporları','Değerleme raporu'], 'Patentli teknolojilerin teknoloji sağlayıcıdan müşteri kuruluşlara transfer edilmesi ve sanayileştirilmesi.', 'open'),
  ('Siparişe Dayalı Ar-Ge Projeleri için KOBİ Destekleme Çağrısı', 'TÜBİTAK', 'kamu', 'Proje bütçesi en fazla 10.000.000 TL', 2, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1707 kodlu çağrı. Müşteri ve tedarikçi kuruluş işbirliğiyle ticarileşme potansiyeli yüksek Ar-Ge projelerini destekler.', '1707', '', '13.11.2026', 'En fazla 24 ay', '10.000.000 TL', 'Kamu hibe tutarının %40''ı; müşteri kuruluş en az %40 ödeme', ARRAY['Müşteri ve KOBİ tedarikçi kuruluşun ortak başvurusu','İlişkili kişi kapsamı dışında ortak proje','İşbirliği sözleşmesi','Müşteri kuruluşun en az %40 ödeme yapması'], ARRAY['Proje önerisi','Ekonomik fizibilite raporu','İşbirliği sözleşmesi','Teknik proje dosyası'], 'Hızlı ürüne dönüşebilecek, ticarileşme potansiyeli yüksek Ar-Ge projelerinin müşteri-tedarikçi işbirliğiyle finanse edilmesi.', 'open'),
  ('Yapay Zekâ Ekosistem Çağrısı', 'TÜBİTAK', 'kamu', 'Proje bütçesi en fazla 10.000.000 TL', 2, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1711 kodlu Yapay Zekâ Ekosistem çağrısı. Müşteri kuruluşların yapay zekâ ihtiyaçlarını ürün veya çözüme dönüştürür.', '1711', '', '02.10.2026', 'En fazla 24 ay', '10.000.000 TL', 'KOBİ müşteri %70; büyük müşteri %60; kamu/üniversite %100', ARRAY['Konsorsiyum kurulması','En az 1 yapay zekâ KOBİ ve en az 1 üniversite/araştırma birimi','Müşteri kuruluşun teknoloji ihtiyacı','Proje ekibinde yapay zekâ ve alan uzmanları'], ARRAY['Ön kayıt formu','Proje önerisi','Niyet beyanı','İşbirliği sözleşmesi'], 'Yapay zekâ teknolojilerinin müşteri kuruluş ihtiyaçlarına uygun ürün ve çözümlere dönüştürülmesi.', 'open'),
  ('Yatırım Tabanlı Girişimcilik Destek Programı (BiGG Yatırım)', 'TÜBİTAK', 'kamu', 'Aşama 2: 1.350.000 TL; temiz teknolojide 900.000 TL', 1, 5, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1812 kodlu program. Teknoloji ve yenilik odaklı fikirlerin girişimlere dönüştürülmesi için yatırım ve hızlandırma desteği sağlar.', '1812', '', '30.09.2026', 'Aşama 2 en fazla 18 ay; Aşama 3 36 ay', '1.350.000 TL yatırım; temiz teknolojide 900.000 TL', '%3 hisse karşılığı yatırım', ARRAY['Üniversite öğrencisi veya mezunu girişimci','Daha önce ilgili BiGG/Teknogirişim desteği almamış olmak','Aşama 2 için iş planı ve uygulayıcı kuruluş onayı','Yatırım ve pay sahipliği sözleşmesi'], ARRAY['Güncel öğrenci belgesi veya mezuniyet belgesi','Yurtdışı mezunları için YÖK denklik belgesi','İş planı','Varsa Ar-Ge proje çıktıları','Etki kurul belgesi'], 'Erken aşama teknoloji fikirlerinin katma değerli işletmelere ve istihdam potansiyeli yüksek girişimlere dönüştürülmesi.', 'open'),
  ('Yeşil İnovasyon Teknoloji Mentörlük Çağrısı', 'TÜBİTAK', 'kamu', 'Program bütçesi üst limiti 310.000 TL', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','tarim'], '1831 kodlu sürekli açık çağrı. KOBİ''lerin yeşil dönüşüm mevzuatına uyumu için teknik danışmanlık ve kapasite analizini destekler.', '1831', '', 'Sürekli açık', 'En az 3 ay, en fazla 6 ay', '310.000 TL', 'Hizmet bedelinin %90''ı TÜBİTAK hibesi', ARRAY['Küçük ve orta büyüklükte Türkiye''de yerleşik KOBİ','Ortaklı başvuru kabul edilmez','Bir KOBİ en fazla 3 kez destek alabilir'], ARRAY['Dönem raporu','Teknik rapor','Hizmet alım faturası','Ödeme belgesi/banka dekontu'], 'Yeşil dönüşüm mevzuatına uyum için danışmanlık, kapasite analizi ve çözüm önerisi desteği.', 'open'),
  ('Sanayide Yeşil Dönüşüm Çağrısı (2026-2)', 'TÜBİTAK', 'kamu', 'Mikro/küçük 15M TL; orta 24M TL; büyük 51,5M TL', 3, 9, ARRAY['yazilim','imalat','enerji','tarim'], '1832 kodlu çağrı. Firmaların yeşil dönüşüm faaliyetlerine yönelik THS 3-9 Ar-Ge çalışmalarını destekler.', '1832', '', '12.10.2026', 'En fazla 24 ay', 'Mikro/küçük 15M TL; orta 24M TL; büyük 51,5M TL', 'Büyük %70; KOBİ %80; deprem bölgesi KOBİ %90; hibeye dönüşüm oranı ayrıca belirlenir', ARRAY['Türkiye''de yerleşik sermaye şirketi','Tescil tarihi 2 yıl ve üzeri','Yürütücü kuruluşun en az %75 özel sektör olması','En az bir Yeşil Dönüşüm Göstergesi hedefi'], ARRAY['Proje önerisi (PRODİS)','Ekonomik fizibilite raporu','Çevresel ve Sosyal Risk Yönetimi Beyan Formu','Banka Referans Mektubu','Vergi beyannamesi','Spin-off değerlendirme formu'], 'Temiz enerji, kaynak verimliliği, döngüsel ekonomi ve sürdürülebilir üretim odaklı sanayi Ar-Ge projeleri.', 'open'),
  ('SAYEM Yeşil Dönüşüm Çağrısı (2026-1)', 'TÜBİTAK', 'kamu', 'Kuruluş başına 28M/70M TL; platform toplam 1,5B TL', 3, 9, ARRAY['yazilim','imalat','enerji','biyoteknoloji','tarim'], '1833 kodlu platform çağrısı. Kurumlar ve yürütücü kuruluşların ortaklığıyla yüksek katma değerli yeşil ürün ve süreçlerin geliştirilmesini sağlar.', '1833', '', 'Kapalı; yeni çağrı bekleniyor', 'En fazla 30 ay, uzatmayla 36 ay', 'Kuruluş başına 28M veya 70M TL; platform toplamı 1,5 milyar TL', 'KOBİ %20-%80; büyük %30-%70 geri ödemeli; deprem bölgesi KOBİ %10-%90', ARRAY['Yürütücü olarak büyük veya orta ölçekli sermaye şirketi','Platformda en az 3 ortak, en fazla 10 ortak','En az bir Yeşil Dönüşüm Göstergesi','Lisans dereceli personel','Çevresel ve sosyal uygunluk'], ARRAY['Ürünleştirme Programı Önerisi','Tanıtım sunumu ve videosu','Ekonomik fizibilite raporu','İşbirliği sözleşmesi','Fikri sınai mülkiyet hakları sözleşmesi','Çevresel ve Sosyal Risk Yönetimi Beyan Formu','Banka referans mektubu','Ortaklık yapısı belgesi','Spin-off formu','Ar-Ge harcamaları raporu','Son yıl kurumlar vergisi beyannamesi'], 'Kurumlar ve platform ortaklarının birlikte yürüttüğü yüksek katma değerli yeşil ürün ve süreç geliştirme programı.', 'open'),
  ('Uluslararası Sanayi Ar-Ge Projeleri Destekleme Programı', 'TÜBİTAK', 'ab', 'Tek ortaklı 25M TL; ortaklı toplam 80M TL', 3, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1509 kodlu uluslararası ortaklı program. Türk firmalarının uluslararası Ar-Ge ve yenilik projeleriyle teknik yeterliliğini ve ihracat kapasitesini artırır.', '1509', '', 'Sürekli açık', 'Proje takvimine göre', 'Tek ortaklı 25M TL; ortaklı toplam 80M TL', 'KOBİ ilk 5 proje %75, sonrası %60; büyük %60, sonrası %40', ARRAY['Türkiye''de yerleşik sermaye şirketi','Uluslararası Ar-Ge ve yenilik projesi','Proje ekibinde ilgili lisans mezunu','Uluslararası ortak/partner'], ARRAY['1509 kılavuzu (AGY103-02)','Uluslararası ortaklık anlaşması','Teknik proje planı','Bütçe planı'], 'Uluslararası ortaklarla yürütülen Ar-Ge ve yenilik projelerinde teknik yeterlilik ve pazar erişimi desteği.', 'open'),
  ('EUREKA-EUROSTARS (Eurostars-3 Ulusal Çağrısı 2026/2)', 'TÜBİTAK / EUREKA', 'ab', 'Ulusal çağrı bütçesi 4.000.000 EUR', 4, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1709 kodlu Eurostars uluslararası ortaklı çağrı. Pazar odaklı yenilikçi ürün, süreç ve hizmet geliştirme projelerini destekler.', '1709', '', '24.09.2026', 'En fazla 36 ay', 'Türk ortak başına 600.000 EUR; ortaklı proje bütçesi 850.000 EUR', 'KOBİ %75; büyük %60; kamu/üniversite/hastane/araştırma merkezi %100', ARRAY['Eurostars uluslararası çağrısına başvuru','En az bir Türk ve bir Eurostars ülke ortağı','Konsorsiyum ve proje yürütücüsü KOBİ','Projede doktoralı veya uzman personel'], ARRAY['Uluslararası başvuru formu','Güncel kurumlar vergisi beyannamesi','Firma imza sirküleri','Proje ekibi özgeçmişleri','Proje önerisi','Konsorsiyum anlaşması'], 'Uluslararası pazara yönelik yenilikçi ürün, süreç ve hizmet geliştirme projeleri.', 'open'),
  ('Eureka Network Çağrıları', 'EUREKA', 'ab', 'Çağrı duyurusuna göre', 3, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], '1719 kodlu Eureka Network çağrıları. Piyasaya sürülebilir ürün, süreç veya hizmet ortaya koyan uluslararası Ar-Ge projelerini destekler.', '1719', '', 'Çağrıya bağlı', 'Çağrı duyurusuna göre', 'Çağrı duyurusuna göre', 'Büyük %60; KOBİ %75; kamu/üniversite/araştırma merkezi %100', ARRAY['Sermaye şirketi kurulmuş olması','Akademik kurumların en az bir sermaye şirketi ortağıyla başvurması','Ayrıntılı çağrı duyurusuna uygun konsorsiyum'], ARRAY['Çağrı duyurusuna göre','Uluslararası ortaklık ve proje önerisi','Bütçe planı'], 'Uluslararası ortaklı, piyasaya sürülebilir ürün, süreç veya hizmet geliştirme projeleri.', 'open'),
  ('Eureka-Seyahat Desteği', 'EUREKA / TÜBİTAK', 'ab', 'Bilgi bulunmuyor', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], 'Eureka çağrılarına başvuracak Türkiye''de yerleşik şirket temsilcilerinin konsorsiyum kurma seyahatlerini destekleyen program.', 'EUREKA-SEYAHAT', '', 'Bilgi yok', 'Bilgi yok', 'Bilgi yok', 'Bilgi yok', ARRAY['Eureka çağrısına başvurabilecek Türkiye''de yerleşik şirket temsilcisi','Çağrı sayfasındaki seyahat şartları'], ARRAY['Başvuru formu şablonu','Seyahat ve toplantı planı','Şirket bilgileri'], 'Eureka uluslararası Ar-Ge projeleri için konsorsiyum kurmaya yönelik seyahat giderleri.', 'open'),
  ('Eurostars Koordinatörlük Desteği Programı', 'EUREKA / TÜBİTAK', 'ab', 'Bilgi bulunmuyor', 3, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], 'Eurostars projelerinde koordinatör olmayı hedefleyen yenilikçi KOBİ''lerin koordinasyon giderlerini destekler.', 'EUROSTARS-KOORD', '', 'Çağrıya bağlı', 'Bilgi yok', 'Bilgi yok', 'Bilgi yok', ARRAY['Türkiye''de yerleşik yenilikçi KOBİ','Eurostars projesinde koordinatörlük hedefi','Çağrı duyurusundaki güncel şartlar'], ARRAY['Koordinatörlük genel başvuru formu','Proje yazma-sunma eğitim planı','Koordinasyon bütçesi'], 'Eurostars projelerinde koordinatörlük, proje yazma ve sunma hizmet giderleri.', 'open'),
  ('Ufuk-Avrupa Programı (TÜBİTAK sayfası)', 'TÜBİTAK / Avrupa Birliği', 'ab', 'Çağrı duyurusuna göre', 1, 9, ARRAY['yazilim','imalat','biyoteknoloji','enerji','savunma','tarim'], 'Ufuk-Avrupa programı için TÜBİTAK bilgilendirme ve yönlendirme kaydı. Güncel proje çağrıları resmi program sayfasından takip edilir.', 'UFUK-AVRUPA', '', 'Bilgi yok', 'Çağrı duyurusuna göre', 'Çağrı duyurusuna göre', 'Çağrı duyurusuna göre', ARRAY['Ufuk-Avrupa çağrı şartlarına uygunluk','Uluslararası konsorsiyum ve proje konusu','TÜBİTAK ve AB program koşullarının birlikte incelenmesi'], ARRAY['Çağrıya özel başvuru formu','Konsorsiyum belgeleri','Teknik proje önerisi','Bütçe ve etki planı'], 'Avrupa Birliği araştırma ve inovasyon çağrılarına erişim ve uluslararası proje geliştirme.', 'open')
) AS seed(name, provider, type, budget, min_trl, max_trl, sectors, description, code, application_url, deadline, duration, max_budget_per_project, support_rate, eligibility, required_docs, technical_scope, status)
WHERE NOT EXISTS (
  SELECT 1 FROM funds existing WHERE existing.code = seed.code OR existing.name = seed.name
);